### DISCUSSION TITLE
Conference XML

### DISCUSSION THREAD

**Discussion by gavinsmith8181** [rtckit/eqivo#21] [Ideas]
Hey! was wondering if that's possible to allow clients to use "GetDigits", "Play" and all sorts of XML actions on a conference.

I was trying to Create a conference and then whenever a agents joins the conference to trigger some kind of IVR for the client, but whenever i transfer the client to a new XML, it just hangup the call.

Was wondering if there is any workaround to use Conference and Transfer Call as well.

**Comment by cdosoftei** [comment]
Hello! The desired behaviour is definitely achievable, albeit not via RestXML but through callbacks (webhooks) as well as the RestAPI.

To collect DTMF tones whilst in a [Conference](https://eqivo.org/#conference), be sure to set the `digitsMatch` attribute, for example:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<Response>
    <Conference digitsMatch="0,1,2,3,4,5,6,7,8,9,*,#" callbackUrl="https://your.host/webhook">TestConf</Conference>
</Response>
```

Once in a conference, as soon as the DMTF input matches one of defined patterns (in this example it would match all tones generate by a typical keypad), it will reach out to the `callbackUrl` with a payload including the matched pattern, e.g.:

```yaml
  "To": "2000000001",
  "Direction": "inbound",
  "From": "10001",
  "CallerName": "10001",
  "CallUUID": "abdeea08-5dc5-473f-aaa0-91f03ce863d1",
  "CallStatus": "in-progress",
  "CoreUUID": "c7e8333a-2b81-4947-8d18-3bdbcff47253",
  "RestApiServer": "10.0.0.101",
  "ConferenceAction": "digits",
  "ConferenceName": "TestConf",
  "ConferenceUUID": "b53a09b0-5e72-46d8-8424-0e3b00f7f58d",
  "ConferenceMemberID": "97",
  "ConferenceDigitsMatch": "5"
```

`ConferenceDigitsMatch` would be the key parameter in this case.

To playback audio to one or more (or all) conference participants, look no further than the [Conference Play](https://eqivo.org/#v0-1-conferenceplay) RestAPI.

Let me know if this works for your use case!
